version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: debian-slave
    image: paulo866/debian-slave-jenkins:1.0.6
    # build:
    # context: slave-linux-dockerfile
    expose:
      - 22
    networks:
      - net
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqubedb:5432/sonar
    volumes:
      - $PWD/sonarqube/conf:/opt/sonarqube/conf
      - $PWD/sonarqube/data:/opt/sonarqube/data
      - $PWD/sonarqube/extensions:/opt/sonarqube/extensions
      - $PWD/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - net
  db:
    container_name: sonarqubedb
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - $PWD/postgresql:/var/lib/postgresql
      - $PWD/postgresql_data:/var/lib/postgresql/data
    networks:
      - net
networks:
  net: