version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: debian-slave
    image: paulo866/debian-slave-jenkins:1.0.6
    # build:
    # context: slave-linux-dockerfile
    expose:
      - 22
    networks:
      - net
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqubedb:5432/sonar
    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - net
  db:
    container_name: sonarqubedb
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
      - ./volumes/postgresql_data:/var/lib/postgresql/data
    networks:
      - net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

networks:
  net: