version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    ports:
      - "9001:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
     container_name: debian-slave
     image: paulo866/debian-slave-jenkins:1.0.0
     # build:
       # context: slave-linux-dockerfile
     networks:
       - net
networks:
  net: